// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VysyxSoCFull.h for the primary calling header

#ifndef VERILATED_VYSYXSOCFULL_YSYXSOCASIC_H_
#define VERILATED_VYSYXSOCFULL_YSYXSOCASIC_H_  // guard

#include "verilated.h"
class VysyxSoCFull_APBUart16550;
class VysyxSoCFull_CPU;


class VysyxSoCFull__Syms;

class alignas(VL_CACHE_LINE_BYTES) VysyxSoCFull_ysyxSoCASIC final : public VerilatedModule {
  public:
    // CELLS
    VysyxSoCFull_CPU* cpu;
    VysyxSoCFull_APBUart16550* luart;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clock,0,0);
        VL_IN8(__PVT__reset,0,0);
        VL_OUT8(__PVT__spi_sck,0,0);
        VL_OUT8(__PVT__spi_ss,7,0);
        VL_OUT8(__PVT__spi_mosi,0,0);
        VL_IN8(__PVT__spi_miso,0,0);
        VL_IN8(__PVT__uart_rx,0,0);
        VL_OUT8(__PVT__uart_tx,0,0);
        VL_OUT8(__PVT__psram_sck,0,0);
        VL_OUT8(__PVT__psram_ce_n,0,0);
        VL_IN8(__PVT__psram_dio,3,0);
        VL_OUT8(__PVT__sdram_clk,0,0);
        VL_OUT8(__PVT__sdram_cke,0,0);
        VL_OUT8(__PVT__sdram_cs,0,0);
        VL_OUT8(__PVT__sdram_ras,0,0);
        VL_OUT8(__PVT__sdram_cas,0,0);
        VL_OUT8(__PVT__sdram_we,0,0);
        VL_OUT8(__PVT__sdram_ba,2,0);
        VL_OUT8(__PVT__sdram_dqm,3,0);
        VL_OUT8(__PVT__gpio_seg_0,7,0);
        VL_OUT8(__PVT__gpio_seg_1,7,0);
        VL_OUT8(__PVT__gpio_seg_2,7,0);
        VL_OUT8(__PVT__gpio_seg_3,7,0);
        VL_OUT8(__PVT__gpio_seg_4,7,0);
        VL_OUT8(__PVT__gpio_seg_5,7,0);
        VL_OUT8(__PVT__gpio_seg_6,7,0);
        VL_OUT8(__PVT__gpio_seg_7,7,0);
        VL_IN8(__PVT__ps2_clk,0,0);
        VL_IN8(__PVT__ps2_data,0,0);
        VL_OUT8(__PVT__vga_r,7,0);
        VL_OUT8(__PVT__vga_g,7,0);
        VL_OUT8(__PVT__vga_b,7,0);
        VL_OUT8(__PVT__vga_hsync,0,0);
        VL_OUT8(__PVT__vga_vsync,0,0);
        VL_OUT8(__PVT__vga_valid,0,0);
        CData/*0:0*/ __PVT___lspi_auto_in_pslverr;
        CData/*0:0*/ __PVT___lvga_auto_in_pready;
        CData/*0:0*/ __PVT___lvga_auto_in_pslverr;
        CData/*0:0*/ __PVT___lkeyboard_auto_in_pready;
        CData/*0:0*/ __PVT___lkeyboard_auto_in_pslverr;
        CData/*0:0*/ __PVT___lgpio_auto_in_pready;
        CData/*0:0*/ __PVT___lgpio_auto_in_pslverr;
        VL_OUT8(psram_dio__out,3,0);
        VL_OUT8(psram_dio__en,3,0);
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_awready;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_awvalid;
        CData/*3:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_awid;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_awsize;
        CData/*1:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_awburst;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_wready;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_wvalid;
        CData/*3:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_wstrb;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_bready;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_bvalid;
        CData/*1:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_bresp;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_arready;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_arvalid;
        CData/*3:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_arid;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_arsize;
        CData/*1:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_arburst;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_rlast;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_out_2_awready;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_out_2_awvalid;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_out_2_bready;
    };
    struct {
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_out_2_arready;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__auto_anon_out_2_rready;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__in_0_wready;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__in_0_awready;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__requestARIO_0_0;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__requestARIO_0_1;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__requestARIO_0_2;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__requestAWIO_0_0;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__requestAWIO_0_2;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT___arFIFOMap_15_T_1;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT___arFIFOMap_15_T_4;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_0_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT___awFIFOMap_15_T_1;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT___awFIFOMap_15_T_4;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_0_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_1_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_1_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_2_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_2_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_3_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_3_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_4_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_4_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_5_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_5_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_6_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_6_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_7_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_7_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_8_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_8_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_9_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_9_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_10_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_10_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_11_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_11_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_12_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_12_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_13_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_13_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_14_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_14_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__arFIFOMap_15_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awFIFOMap_15_count;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__latched;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT___anonIn_awready_T;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__in_0_awvalid;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__in_0_wvalid;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__idle_3;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__anyValid;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__readys_valid;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__readys_mask;
        CData/*5:0*/ __PVT__axi4xbar_1__DOT__readys_unready;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__readys_readys;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__prefixOR_1;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__winner_3_1;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__winner_3_2;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__state_3_0;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__state_3_1;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__state_3_2;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__muxState_3_0;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__muxState_3_1;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__muxState_3_2;
    };
    struct {
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__idle_4;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__anyValid_1;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__readys_valid_1;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__readys_mask_1;
        CData/*5:0*/ __PVT__axi4xbar_1__DOT__readys_unready_1;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__readys_readys_1;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__winner_4_0;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__winner_4_2;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__state_4_0;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__state_4_2;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__muxState_4_0;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__muxState_4_2;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__unnamedblk1__DOT___readys_mask_T;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__unnamedblk1__DOT___readys_mask_T_3;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__unnamedblk2__DOT___readys_mask_T_8;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__unnamedblk2__DOT___readys_mask_T_11;
        CData/*0:0*/ axi4xbar_1__DOT____VdfgRegularize_hc1964d0a_0_0;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__io_enq_valid;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__io_deq_ready;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__io_deq_valid;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__io_deq_bits;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__wrap;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__wrap_1;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__maybe_full;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__ptr_match;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__empty;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__full;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__do_deq;
        CData/*0:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__ram_ext__DOT__W0_en;
        CData/*2:0*/ __PVT__axi4xbar_1__DOT__awIn_0__DOT__ram_ext__DOT__W0_data;
        CData/*0:0*/ __PVT__apbxbar__DOT__sel_0;
        CData/*0:0*/ __PVT__apbxbar__DOT__sel_1;
        CData/*0:0*/ __PVT__apbxbar__DOT__sel_2;
        CData/*0:0*/ __PVT__apbxbar__DOT__sel_3;
        CData/*0:0*/ __PVT__apbxbar__DOT__sel_4;
        CData/*0:0*/ __PVT__apbxbar__DOT__sel_5;
        CData/*0:0*/ __PVT__apbxbar__DOT__sel_6;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__in_psel;
        CData/*7:0*/ __PVT__lspi__DOT__mspi__DOT__spi_ss;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__spi_irq_out;
        CData/*1:0*/ __PVT__lspi__DOT__mspi__DOT__state;
        CData/*1:0*/ __PVT__lspi__DOT__mspi__DOT__next_state;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__xipmaster_pready;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__xipmaster_pslverr;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__xipmaster_irq_out;
        CData/*4:0*/ __PVT__lspi__DOT__mspi__DOT__xipslv_paddr;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__xipslv_psel;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__xipslv_penable;
        CData/*2:0*/ __PVT__lspi__DOT__mspi__DOT__xipslv_pprot;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__xipslv_pwrite;
        CData/*3:0*/ __PVT__lspi__DOT__mspi__DOT__xipslv_pstrb;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__xipslv_pready;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__xipslv_irq_out;
        CData/*4:0*/ __PVT__lspi__DOT__mspi__DOT__spictrl_paddr;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__spictrl_psel;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__spictrl_penable;
        CData/*2:0*/ __PVT__lspi__DOT__mspi__DOT__spictrl_pprot;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__spictrl_pwrite;
        CData/*3:0*/ __PVT__lspi__DOT__mspi__DOT__spictrl_pstrb;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__spictrl_pready;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__spictrl_irq_out;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__wb_psel_i;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__wb_penable_i;
        CData/*3:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__sstate;
    };
    struct {
        CData/*3:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__next_sstate;
        CData/*3:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__state;
        CData/*3:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__next_state;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__is_transfer;
        CData/*4:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__buf_paddr;
        CData/*3:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__buf_pstrb;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__buf_pwrite;
        CData/*7:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__ss;
        CData/*3:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__spi_tx_sel;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__tip;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__pos_edge;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__neg_edge;
        CData/*0:0*/ lspi__DOT__mspi__DOT__u0_spi_top__DOT____VdfgRegularize_h189b3b9c_0_0;
        CData/*0:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__clgen__DOT__cnt_zero;
        CData/*3:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__shift__DOT__latch;
        CData/*7:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__shift__DOT__cnt;
        CData/*7:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__shift__DOT__rx_bit_pos;
        CData/*7:0*/ lspi__DOT__mspi__DOT__u0_spi_top__DOT__shift__DOT____VdfgRegularize_ha14fb189_0_0;
        CData/*3:0*/ lpsram__DOT__mpsram__DOT__qspi_dio__out__strong__out0;
        CData/*3:0*/ lpsram__DOT__mpsram__DOT__qspi_dio__out__strong__out1;
        CData/*3:0*/ lpsram__DOT__mpsram__DOT__qspi_dio__out__strong__out2;
        CData/*3:0*/ lpsram__DOT__mpsram__DOT__qspi_dio__out__strong__out3;
        CData/*3:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__sel_i;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__cyc_i;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__we_i;
        CData/*3:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__dout;
        CData/*3:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__douten;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__mr_sck;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__mr_ce_n;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__mw_sck;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__mw_ce_n;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__qpi_sck;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__qpi_ce_n;
        CData/*3:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__qpi_din;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__wb_we;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__wb_re;
        CData/*1:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__state;
        CData/*1:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__nstate;
        CData/*2:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__size;
        CData/*7:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__byte0;
        CData/*7:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__byte1;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MR__DOT__rd;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MR__DOT__done;
        CData/*3:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MR__DOT__din;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MR__DOT__state;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MR__DOT__nstate;
        CData/*7:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MR__DOT__counter;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MW__DOT__wr;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MW__DOT__done;
        CData/*3:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MW__DOT__dout;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MW__DOT__state;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MW__DOT__nstate;
        CData/*7:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MW__DOT__counter;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__QPI__DOT__done;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__QPI__DOT__state;
        CData/*0:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__QPI__DOT__nstate;
        CData/*7:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__QPI__DOT__counter;
        CData/*0:0*/ __PVT__lmrom__DOT__state;
        CData/*0:0*/ __PVT__lmrom__DOT___nodeIn_rid_T;
        CData/*3:0*/ __PVT__lmrom__DOT__nodeIn_rid_r;
        CData/*0:0*/ __PVT__axi4ram__DOT__w_full;
        CData/*3:0*/ __PVT__axi4ram__DOT__w_id;
        CData/*0:0*/ __PVT__axi4ram__DOT__r_sel1;
        CData/*0:0*/ __PVT__axi4ram__DOT__w_sel1;
    };
    struct {
        CData/*0:0*/ __PVT__axi4ram__DOT___GEN;
        CData/*0:0*/ __PVT__axi4ram__DOT__r_full;
        CData/*3:0*/ __PVT__axi4ram__DOT__r_id;
        CData/*0:0*/ __PVT__axi4ram__DOT__rdata_REG;
        CData/*7:0*/ __PVT__axi4ram__DOT__rdata_r0;
        CData/*7:0*/ __PVT__axi4ram__DOT__rdata_r1;
        CData/*7:0*/ __PVT__axi4ram__DOT__rdata_r2;
        CData/*7:0*/ __PVT__axi4ram__DOT__rdata_r3;
        CData/*0:0*/ axi4ram__DOT____VdfgRegularize_h9fc36335_0_0;
        CData/*0:0*/ __PVT__axi4ram__DOT__mem_ext__DOT__R0_en;
        CData/*0:0*/ __PVT__axi4ram__DOT__mem_ext__DOT__W0_en;
        CData/*0:0*/ __PVT__axi4ram__DOT__mem_ext__DOT___R0_en_d0;
        CData/*1:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__state;
        CData/*0:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__is_write;
        CData/*3:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__inport_wr_i;
        CData/*0:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__inport_rd_i;
        CData/*0:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__ram_req_w;
        CData/*3:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__command_q;
        CData/*0:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__data_rd_en_q;
        CData/*3:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__dqm_q;
        CData/*0:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__cke_q;
        CData/*2:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__bank_q;
        CData/*3:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__dqm_buffer_q;
        CData/*0:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__refresh_q;
        CData/*7:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__row_open_q;
        CData/*3:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__state_q;
        CData/*3:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__next_state_r;
        CData/*3:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__target_state_r;
        CData/*3:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__target_state_q;
        CData/*3:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__delay_state_q;
        CData/*3:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__delay_q;
        CData/*3:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__delay_r;
        CData/*2:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__rd_q;
        CData/*0:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__ack_q;
        CData/*0:0*/ __PVT__apbdelay_delayer__DOT__in_psel;
        CData/*0:0*/ __PVT__apbdelay_delayer__DOT__in_pready;
        CData/*0:0*/ __PVT__apbdelay_delayer__DOT__in_pslverr;
        CData/*0:0*/ __PVT__axi42apb__DOT__auto_in_awready;
        CData/*0:0*/ __PVT__axi42apb__DOT__auto_in_bvalid;
        CData/*1:0*/ __PVT__axi42apb__DOT__auto_in_bresp;
        CData/*0:0*/ __PVT__axi42apb__DOT__auto_in_arready;
        CData/*0:0*/ __PVT__axi42apb__DOT__auto_in_rvalid;
        CData/*1:0*/ __PVT__axi42apb__DOT__state;
        CData/*0:0*/ __PVT__axi42apb__DOT__is_write_r;
        CData/*3:0*/ __PVT__axi42apb__DOT__rid_reg;
        CData/*3:0*/ __PVT__axi42apb__DOT__bid_reg;
        CData/*3:0*/ __PVT__axi42apb__DOT__wstrb_reg_r;
        CData/*1:0*/ __PVT__axi42apb__DOT__resp_hold_r;
        CData/*7:0*/ __PVT__axi42apb__DOT__unnamedblk1__DOT___GEN;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_awdeq_q__DOT__wrap;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_awdeq_q__DOT__wrap_1;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_awdeq_q__DOT__maybe_full;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_awdeq_q__DOT__ptr_match;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_awdeq_q__DOT__empty;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_awdeq_q__DOT__full;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_awdeq_q__DOT__unnamedblk1__DOT__do_deq;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_awdeq_q__DOT__ram_ext__DOT__W0_en;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_wdeq_q__DOT__wrap;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_wdeq_q__DOT__wrap_1;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_wdeq_q__DOT__maybe_full;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_wdeq_q__DOT__ptr_match;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_wdeq_q__DOT__empty;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_wdeq_q__DOT__full;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_wdeq_q__DOT__unnamedblk1__DOT__do_deq;
    };
    struct {
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_wdeq_q__DOT__ram_ext__DOT__W0_en;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_bdeq_q__DOT__wrap;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_bdeq_q__DOT__wrap_1;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_bdeq_q__DOT__maybe_full;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_bdeq_q__DOT__ptr_match;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_bdeq_q__DOT__empty;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_bdeq_q__DOT__full;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_bdeq_q__DOT__unnamedblk1__DOT__do_deq;
        CData/*5:0*/ __PVT__axi4buf__DOT__nodeIn_bdeq_q__DOT__ram_ext__DOT__R0_data;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_bdeq_q__DOT__ram_ext__DOT__W0_en;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_ardeq_q__DOT__wrap;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_ardeq_q__DOT__wrap_1;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_ardeq_q__DOT__maybe_full;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_ardeq_q__DOT__ptr_match;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_ardeq_q__DOT__empty;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_ardeq_q__DOT__full;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_ardeq_q__DOT__unnamedblk1__DOT__do_deq;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeOut_ardeq_q__DOT__ram_ext__DOT__W0_en;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_rdeq_q__DOT__wrap;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_rdeq_q__DOT__wrap_1;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_rdeq_q__DOT__maybe_full;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_rdeq_q__DOT__ptr_match;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_rdeq_q__DOT__empty;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_rdeq_q__DOT__full;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_rdeq_q__DOT__unnamedblk1__DOT__do_deq;
        CData/*0:0*/ __PVT__axi4buf__DOT__nodeIn_rdeq_q__DOT__ram_ext__DOT__W0_en;
        CData/*0:0*/ __PVT__axi4yank__DOT__auto_in_awready;
        CData/*0:0*/ __PVT__axi4yank__DOT__auto_in_awvalid;
        CData/*0:0*/ __PVT__axi4yank__DOT__auto_in_becho_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__auto_in_arready;
        CData/*0:0*/ __PVT__axi4yank__DOT__auto_in_arvalid;
        CData/*0:0*/ __PVT__axi4yank__DOT___GEN_2;
        CData/*0:0*/ __PVT__axi4yank__DOT___GEN_8;
        CData/*0:0*/ axi4yank__DOT____VdfgRegularize_h6c436e9c_0_0;
        CData/*0:0*/ axi4yank__DOT____VdfgRegularize_h6c436e9c_0_1;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_1__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_1__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_1__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_2__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_2__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_2__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_3__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_3__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_3__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_4__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_4__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_4__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_5__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_5__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_5__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_6__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_6__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_6__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_7__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_7__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_7__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_8__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_8__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_8__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_9__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_9__DOT__ram_real_last;
    };
    struct {
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_9__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_10__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_10__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_10__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_11__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_11__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_11__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_12__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_12__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_12__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_13__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_13__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_13__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_14__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_14__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_14__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_15__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_15__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_15__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_16__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_16__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_16__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_17__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_17__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_17__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_18__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_18__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_18__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_19__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_19__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_19__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_20__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_20__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_20__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_21__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_21__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_21__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_22__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_22__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_22__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_23__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_23__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_23__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_24__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_24__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_24__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_25__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_25__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_25__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_26__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_26__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_26__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_27__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_27__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_27__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_28__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_28__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_28__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_29__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_29__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_29__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_30__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_30__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_30__DOT__unnamedblk1__DOT__do_enq;
    };
    struct {
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_31__DOT__full;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_31__DOT__ram_real_last;
        CData/*0:0*/ __PVT__axi4yank__DOT__Queue1_BundleMap_31__DOT__unnamedblk1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4frag__DOT__in_awready;
        CData/*0:0*/ __PVT__axi4frag__DOT__busy;
        CData/*7:0*/ __PVT__axi4frag__DOT__r_len;
        CData/*7:0*/ __PVT__axi4frag__DOT__len;
        CData/*0:0*/ __PVT__axi4frag__DOT__busy_1;
        CData/*7:0*/ __PVT__axi4frag__DOT__r_len_1;
        CData/*7:0*/ __PVT__axi4frag__DOT__len_1;
        CData/*0:0*/ __PVT__axi4frag__DOT__wbeats_latched;
        CData/*0:0*/ __PVT__axi4frag__DOT___in_awready_T;
        CData/*0:0*/ __PVT__axi4frag__DOT__wbeats_valid;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_0;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_1;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_2;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_3;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_4;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_5;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_6;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_7;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_8;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_9;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_10;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_11;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_12;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_13;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_14;
        CData/*1:0*/ __PVT__axi4frag__DOT__error_15;
        CData/*0:0*/ __PVT__axi4frag__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_3;
        CData/*0:0*/ axi4frag__DOT____VdfgRegularize_h068021ff_0_0;
        CData/*0:0*/ __PVT__axi4frag__DOT__deq_q__DOT__io_deq_ready;
        CData/*7:0*/ __PVT__axi4frag__DOT__deq_q__DOT__io_deq_bits_len;
        CData/*0:0*/ __PVT__axi4frag__DOT__deq_q__DOT__full;
        CData/*0:0*/ __PVT__axi4frag__DOT__deq_q__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4frag__DOT__deq_q_1__DOT__io_deq_ready;
        CData/*0:0*/ __PVT__axi4frag__DOT__deq_q_1__DOT__io_deq_valid;
        CData/*7:0*/ __PVT__axi4frag__DOT__deq_q_1__DOT__io_deq_bits_len;
        CData/*0:0*/ __PVT__axi4frag__DOT__deq_q_1__DOT__full;
        CData/*0:0*/ __PVT__axi4frag__DOT__deq_q_1__DOT__do_enq;
        CData/*0:0*/ __PVT__axi4frag__DOT__in_wdeq_q__DOT__io_deq_ready;
        CData/*0:0*/ __PVT__axi4frag__DOT__in_wdeq_q__DOT__io_deq_valid;
        CData/*0:0*/ __PVT__axi4frag__DOT__in_wdeq_q__DOT__full;
        CData/*0:0*/ __PVT__axi4frag__DOT__in_wdeq_q__DOT__do_enq;
        CData/*0:0*/ __PVT__cpu_reset_chain__DOT__output_chain__DOT__sync_0;
        CData/*0:0*/ __PVT__cpu_reset_chain__DOT__output_chain__DOT__sync_1;
        CData/*0:0*/ __PVT__cpu_reset_chain__DOT__output_chain__DOT__sync_2;
        CData/*0:0*/ __PVT__cpu_reset_chain__DOT__output_chain__DOT__sync_3;
        CData/*0:0*/ __PVT__cpu_reset_chain__DOT__output_chain__DOT__sync_4;
        CData/*0:0*/ __PVT__cpu_reset_chain__DOT__output_chain__DOT__sync_5;
        CData/*0:0*/ __PVT__cpu_reset_chain__DOT__output_chain__DOT__sync_6;
        CData/*0:0*/ __PVT__cpu_reset_chain__DOT__output_chain__DOT__sync_7;
        CData/*0:0*/ __PVT__cpu_reset_chain__DOT__output_chain__DOT__sync_8;
        CData/*0:0*/ __PVT__cpu_reset_chain__DOT__output_chain__DOT__sync_9;
        VL_OUT16(__PVT__sdram_a,12,0);
        VL_OUT16(__PVT__gpio_out,15,0);
        VL_IN16(__PVT__gpio_in,15,0);
        SData/*15:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__divider;
        SData/*13:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__ctrl;
        SData/*15:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__clgen__DOT__cnt;
        SData/*10:0*/ __PVT__axi4ram__DOT__mem_ext__DOT___R0_addr_d0;
        SData/*12:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__addr_q;
        SData/*8:0*/ __PVT__axi4frag__DOT__w_counter;
        SData/*8:0*/ __PVT__axi4frag__DOT__w_todo;
    };
    struct {
        SData/*15:0*/ __PVT__axi4frag__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_2;
        VL_IN(__PVT__sdram_dq,31,0);
        IData/*31:0*/ __PVT___lspi_auto_in_prdata;
        IData/*31:0*/ __PVT___lvga_auto_in_prdata;
        IData/*31:0*/ __PVT___lkeyboard_auto_in_prdata;
        IData/*31:0*/ __PVT___lgpio_auto_in_prdata;
        VL_OUT(sdram_dq__out,31,0);
        VL_OUT(sdram_dq__en,31,0);
        IData/*31:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_awaddr;
        IData/*31:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_wdata;
        IData/*31:0*/ __PVT__axi4xbar_1__DOT__auto_anon_in_araddr;
        IData/*31:0*/ __PVT__lspi__DOT__mspi__DOT__xipmaster_prdata;
        IData/*31:0*/ __PVT__lspi__DOT__mspi__DOT__xipslv_pwdata;
        IData/*31:0*/ __PVT__lspi__DOT__mspi__DOT__xipslv_prdata;
        IData/*31:0*/ __PVT__lspi__DOT__mspi__DOT__spictrl_pwdata;
        IData/*31:0*/ __PVT__lspi__DOT__mspi__DOT__spictrl_prdata;
        IData/*31:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__buf_wdata;
        IData/*31:0*/ __PVT__lspi__DOT__mspi__DOT__spi_XIP_inst__DOT__buf_rdata;
        VlWide<4>/*127:0*/ __PVT__lspi__DOT__mspi__DOT__u0_spi_top__DOT__shift__DOT__data;
        IData/*31:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__adr_i;
        IData/*31:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__dat_i;
        IData/*23:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MR__DOT__saddr;
        IData/*23:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MW__DOT__saddr;
        IData/*23:0*/ __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__QPI__DOT__saddr;
        IData/*31:0*/ __PVT__lmrom__DOT___mrom_rdata;
        IData/*31:0*/ __PVT__lmrom__DOT__nodeIn_rdata_r;
        IData/*31:0*/ __PVT__axi4ram__DOT__mem_ext__DOT__R0_data;
        IData/*31:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__sdram_data_input_i;
        IData/*31:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__data_q;
        IData/*31:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__data_buffer_q;
        IData/*16:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__refresh_timer_q;
        IData/*31:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__sample_data0_q;
        IData/*31:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__sample_data_q;
        IData/*31:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__idx;
        VlWide<3>/*79:0*/ __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__dbg_state;
        IData/*31:0*/ __PVT__apbdelay_delayer__DOT__in_prdata;
        IData/*31:0*/ __PVT__axi42apb__DOT__araddr_reg_r;
        IData/*31:0*/ __PVT__axi42apb__DOT__awaddr_reg_r;
        IData/*31:0*/ __PVT__axi42apb__DOT__wdata_reg_r;
        IData/*31:0*/ __PVT__axi42apb__DOT__nodeIn_rdata_r;
        IData/*31:0*/ __PVT__axi4frag__DOT__r_addr;
        IData/*31:0*/ __PVT__axi4frag__DOT__addr;
        IData/*31:0*/ __PVT__axi4frag__DOT__r_addr_1;
        IData/*31:0*/ __PVT__axi4frag__DOT__addr_1;
        IData/*31:0*/ __PVT__axi4frag__DOT__unnamedblk1__DOT__unnamedblk3__DOT___inc_addr_T_1;
        IData/*22:0*/ __PVT__axi4frag__DOT__unnamedblk1__DOT__unnamedblk3__DOT___wrapMask_T_1;
        IData/*31:0*/ __PVT__axi4frag__DOT__unnamedblk1__DOT__unnamedblk3__DOT___mux_addr_T_1;
        IData/*31:0*/ __PVT__axi4frag__DOT__unnamedblk1__DOT__unnamedblk4__DOT___inc_addr_T_3;
        IData/*22:0*/ __PVT__axi4frag__DOT__unnamedblk1__DOT__unnamedblk4__DOT___wrapMask_T_3;
        IData/*31:0*/ __PVT__axi4frag__DOT__unnamedblk1__DOT__unnamedblk4__DOT___mux_addr_T_6;
        IData/*31:0*/ __PVT__axi4frag__DOT__deq_q__DOT__io_deq_bits_addr;
        IData/*31:0*/ __PVT__axi4frag__DOT__deq_q_1__DOT__io_deq_bits_addr;
        IData/*31:0*/ __Vtask_lmrom__DOT__mrom__DOT__mrom_read__0__rdata;
        IData/*16:0*/ __Vdly__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__refresh_timer_q;
        QData/*46:0*/ __PVT__axi4buf__DOT__nodeOut_awdeq_q__DOT__ram_ext__DOT__R0_data;
        QData/*35:0*/ __PVT__axi4buf__DOT__nodeOut_wdeq_q__DOT__ram_ext__DOT__R0_data;
        QData/*46:0*/ __PVT__axi4buf__DOT__nodeOut_ardeq_q__DOT__ram_ext__DOT__R0_data;
        QData/*38:0*/ __PVT__axi4buf__DOT__nodeIn_rdeq_q__DOT__ram_ext__DOT__R0_data;
        QData/*48:0*/ __PVT__axi4frag__DOT__deq_q__DOT__ram;
        QData/*48:0*/ __PVT__axi4frag__DOT__deq_q_1__DOT__ram;
        QData/*36:0*/ __PVT__axi4frag__DOT__in_wdeq_q__DOT__ram;
        VlUnpacked<CData/*2:0*/, 2> __PVT__axi4xbar_1__DOT__awIn_0__DOT__ram_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 4> __PVT__lpsram__DOT__mpsram__DOT__u0__DOT__MR__DOT__data;
        VlUnpacked<IData/*31:0*/, 2048> __PVT__axi4ram__DOT__mem_ext__DOT__Memory;
    };
    struct {
        VlUnpacked<SData/*12:0*/, 8> __PVT__lsdram_apb__DOT__msdram__DOT__u_sdram_ctrl__DOT__active_row_q;
        VlUnpacked<QData/*46:0*/, 2> __PVT__axi4buf__DOT__nodeOut_awdeq_q__DOT__ram_ext__DOT__Memory;
        VlUnpacked<QData/*35:0*/, 2> __PVT__axi4buf__DOT__nodeOut_wdeq_q__DOT__ram_ext__DOT__Memory;
        VlUnpacked<CData/*5:0*/, 2> __PVT__axi4buf__DOT__nodeIn_bdeq_q__DOT__ram_ext__DOT__Memory;
        VlUnpacked<QData/*46:0*/, 2> __PVT__axi4buf__DOT__nodeOut_ardeq_q__DOT__ram_ext__DOT__Memory;
        VlUnpacked<QData/*38:0*/, 2> __PVT__axi4buf__DOT__nodeIn_rdeq_q__DOT__ram_ext__DOT__Memory;
    };

    // INTERNAL VARIABLES
    VysyxSoCFull__Syms* const vlSymsp;

    // CONSTRUCTORS
    VysyxSoCFull_ysyxSoCASIC(VysyxSoCFull__Syms* symsp, const char* v__name);
    ~VysyxSoCFull_ysyxSoCASIC();
    VL_UNCOPYABLE(VysyxSoCFull_ysyxSoCASIC);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
